### PR TITLE
Disable Autopep8 and Yapf if this plugin is installed

### PR DESCRIPTION
**Pull request by bagel897**
This does 3 things:
1. Disable YAPF
2. Disable autopep8
3. change the flake8 config to use a max line length of 88 instead of 80.

### CODE REVIEW

**Comment by haplo** [comment]
This looks good to me, I will try it out later. What do you think @ccordoba12?

**Comment by bageljrkhanofemus** [comment]
I was just wondering if there was a better solution to the conflicts caused by black - since it instantiates a line length of 88 while flake8 uses 80, causing alot of unneeded frustration. But if it is better to do so in your IDE/Editor configuration, could that be added that as an recommendation?

**Comment by ccordoba12** [comment]
> I was just wondering if there was a better solution to the conflicts caused by black

I think we could leave here the configuration entries that disable `autopep8` and `yapf`, if @haplo agrees with it.

> But if it is better to do so in your IDE/Editor configuration, could that be added that as an recommendation?

Sure, for flake8 that's the way to go.

**Comment by bageljrkhanofemus** [comment]
Done, I'll move discussion about flake8 to here https://github.com/python-lsp/python-lsp-server/issues/186

**Comment by haplo** [comment]
> I was just wondering if there was a better solution to the conflicts caused by black - since it instantiates a line length of 88 while flake8 uses 80, causing alot of unneeded frustration. But if it is better to do so in your IDE/Editor configuration, could that be added that as an recommendation?

I think the best way to handle this is through flake8's configuration files, so it would always work, not just python-lsp-server and not just the developers adjusting their IDE configuration.

From black documentation: https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8

**Comment by haplo** [comment]
> > I was just wondering if there was a better solution to the conflicts caused by black
> 
> I think we could leave here the configuration entries that disable `autopep8` and `yapf`, if @haplo agrees with it.

I think it's a good idea, I expect it would be useful to most users. However what would happen to an user that installed _python-lsp-black_ globally but only tried to use it in some projects, while using _yapf_ or _autopep8_ on others? Would manually overriding the configuration work? Whichever way we choose we should document the default behavior and how to override it.

**Comment by bageljrkhanofemus** [comment]
I was going to check how autopep8 and yapf handle it, when I noticed a couple of things
1. While the docs say that yapf is preferred over autopep8, the implementation (if both are installed) is to first call autopep8, then yapf on the same file
2. adding black to the mix (before the merge) would result in it being called first before the others, since we call it with a list of non-disabled plugins. 
I wonder if there is a way to get the PluginManager from pluggy to disable other plugins at runtime

**Review by ccordoba12 — APPROVED** [review]
Looks good to me now, thanks @bageljrkhanofemus!

**Comment by haplo** [comment]
@bageljrkhanofemus Could you update the README to mention that _python-lsp-black_ will by default disable _yapf_ and _autopep8_ plugins from _python-lsp-server_?

**Comment by bageljrkhanofemus** [comment]
done

**Comment by bageljrkhanofemus** [comment]
You need to update black to 22.3.0 for github builds to work because black < 22.3.0 is broken with the latest version of click.. I don't see a dependency specification anywhere but you may want to specify it in a pyproject.toml file for PEP 517/518/621 compliant approach. I can help with that if you want me to.
See https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click for the error.

**Comment by ccordoba12** [comment]
Here you can find the dependency on Black:

https://github.com/python-lsp/python-lsp-black/blob/9c8e61c33dc4a178c74919ecded3f18e8b2c6a19/setup.cfg#L21

Please update it to `22.3.0`. so we can release 1.2.1 with this fix asap.

**Comment by bageljrkhanofemus** [comment]
done

**Comment by ccordoba12** [comment]
Thanks @bageljrkhanofemus for your help to solve the Click issue!

@haplo, what do you say?

**Comment by haplo** [comment]
This looks good to me, thank you @bageljrkhanofemus for your work on this!

I will merge tomorrow and release.

**Pull request merged**
